config/routes.rb
Rails.application.routes.draw do
     
  devise_for :users, controllers: {:registrations => 'admin/registrations', :sessions => 'admin/sessions'}
  
  scope module: 'admin' do
    resources :users, except: [:create]
    resources :users, path: 'my_users', only: [:create]
    resources :departments
    resources :positions
  end

  resources :groups
  resources :company_types
  resources :companies
  resources :contacts
  resources :activity_types
  resources :activities

  get "serve_activities/planned", to: "serve_activities#planned"
  get "serve_activities/completed", to: "serve_activities#completed"

  root to: 'welcome#index'

end

app/models/position.rb
class Position < ActiveRecord::Base
  
  has_many :users

  validates :title, uniqueness: true

end

app/controllers/admin/positions_controller.rb
class Admin::PositionsController < ApplicationController

def index
  @positions = Position.all
end

def new
  @position = Position.new
end

def create
  @position = Position.new(position_params)
  
  if @position.save
    redirect_to positions_path, notice: 'New position created.'
  else
    render 'new'
  end
end    

def edit
  @position = Position.find(params[:id])
end

def update
  @position = Position.find(params[:id])

  if @position.update(position_params)
    redirect_to positions_path, notice: 'Position updated.'
  else
    render 'edit'
  end

end

def destroy
  @position = Position.find(params[:id])
    
    if !@position.users.empty? 
      flash[:alert] = 'Can\'t destroy position. Associated records in users are found.'
    else
      if @position.destroy
        flash[:notice] = 'Position destroyed.'
      else
        flash[:alert] = 'Something went wrong.'
      end
    end
    
    redirect_to positions_path

end

private

def position_params
  params.require(:position).permit(:title)
end

end  

app/views/admin/positions/edit.html.haml
.authform
  = form_for @position, html: {method: :patch, :role => 'form'} do |f|
    %h3 Change position
    - if @position.errors.any?
      #error_explanation
        = render 'shared/messages', obj: @position
    .form-group
      = f.label :title
      = f.text_field :title, autofocus: true, class: 'form-control'
    = f.submit "Change position", :class => 'button right'
    = render "shared/form_nav_links", locals: { back: true }

app/views/admin/positions/index.html.haml
%h3
  List of positions
  %table.my_table
    %thead
      %tr
        %th Title
        %th
    %tbody
      - @positions.each do |dept|  
        %tr
          %td
            =dept.title
          %td
            =link_to 'Edit', edit_position_path(dept)
            =link_to 'Destroy', position_path(dept), method: :delete
    %tfoot
      %tr
        %td
          %strong All positions:
        %td
          %strong
            =@positions.length
%ul.nav.nav-pills
  %li
    =link_to "New position", new_position_path
  %li.active
    =link_to "Home", root_path

app/views/admin/positions/new.html.haml
.authform
  = form_for @position, html: {:role => 'form'} do |f|
    %h3 New position
    - if @position.errors.any?
      #error_explanation
        = render 'shared/messages', obj: @position
    .form-group
      = f.label :title
      = f.text_field :title, autofocus: true, class: 'form-control'
    = f.submit "Add position", :class => 'button right'
    = render "shared/form_nav_links", locals: { back: true }