config/routes.rb
Rails.application.routes.draw do
     
  devise_for :users, controllers: {:registrations => 'admin/registrations', :sessions => 'admin/sessions'}
  
  scope module: 'admin' do
    resources :users, except: [:create]
    resources :users, path: 'my_users', only: [:create]
    resources :departments
    resources :positions
  end

  resources :groups
  resources :company_types
  resources :companies
  resources :contacts
  resources :activity_types
  resources :activities

  get "serve_activities/planned", to: "serve_activities#planned"
  get "serve_activities/completed", to: "serve_activities#completed"

  root to: 'welcome#index'

end

app/models/department.rb
class Department < ActiveRecord::Base

  has_many :users

  validates :title, uniqueness: true

end

app/controllers/admin/departments_controller.rb
class Admin::DepartmentsController < ApplicationController

def index
  @departments = Department.all
end

def new
  @department = Department.new
end

def create
  @department = Department.new(department_params)
  
  if @department.save
    redirect_to departments_path, notice: 'New department created.'
  else
    render 'new'
  end
end    

def edit
  @department = Department.find(params[:id])
end

def update
  @department = Department.find(params[:id])

  if @department.update(department_params)
    redirect_to departments_path, notice: 'Department updated.'
  else
    render 'edit'
  end

end

def destroy
  @department = Department.find(params[:id])
    
    if !@department.users.empty? 
      flash[:alert] = 'Can\'t destroy dept. Associated records in users are found.'
    else
      if @department.destroy
        flash[:notice] = 'Department destroyed.'
      else
        flash[:alert] = 'Something went wrong.'
      end
    end
    
    redirect_to departments_path

end

private

def department_params
  params.require(:department).permit(:title)
end

end  

app/views/admin/departments/edit.html.haml
.authform
  = form_for @department, html: {method: :patch, :role => 'form'} do |f|
    %h3 Change department
    - if @department.errors.any?
      #error_explanation
        = render 'shared/messages', obj: @department
    .form-group
      = f.label :title
      = f.text_field :title, autofocus: true, class: 'form-control'
    = f.submit "Change department", :class => 'button right'
    = render "shared/form_nav_links", locals: { back: true }

app/views/admin/departments/index.html.haml
%h3
  List of departments
  %table.my_table
    %thead
      %tr
        %th Title
        %th
    %tbody
      - @departments.each do |dept|  
        %tr
          %td
            =dept.title
          %td
            =link_to 'Edit', edit_department_path(dept)
            =link_to 'Destroy', department_path(dept), method: :delete
    %tfoot
      %tr
        %td
          %strong All dept:
        %td
          %strong
            =@departments.length
%ul.nav.nav-pills
  %li
    =link_to "New department", new_department_path
  %li.active
    =link_to "Home", root_path

app/views/admin/departments/new.html.haml
.authform
  = form_for @department, html: {:role => 'form'} do |f|
    %h3 New department
    - if @department.errors.any?
      #error_explanation
        = render 'shared/messages', obj: @department
    .form-group
      = f.label :title
      = f.text_field :title, autofocus: true, class: 'form-control'
    = f.submit "Add department", :class => 'button right'
    = render "shared/form_nav_links", locals: { back: true }