config/routes.rb
Rails.application.routes.draw do
     
  devise_for :users, controllers: {:registrations => 'admin/registrations', :sessions => 'admin/sessions'}
  
  scope module: 'admin' do
    resources :users, except: [:create]
    resources :users, path: 'my_users', only: [:create]
    resources :departments
    resources :positions
  end

  resources :groups
  resources :company_types
  resources :companies
  resources :contacts
  resources :activity_types
  resources :activities

  get "serve_activities/planned", to: "serve_activities#planned"
  get "serve_activities/completed", to: "serve_activities#completed"

  root to: 'welcome#index'

end

app/models/group.rb
class Group < ActiveRecord::Base

  has_many :group_users
  has_many :users, through: :group_users
  belongs_to :owner, foreign_key: :created_by, class_name: "User"

  validates :name, presence: true, uniqueness: true

  def update_users(user_ids)
  	self.users = User.where(id: user_ids)
  	self.save
  end
   	
end

app/models/position.rb
class Position < ActiveRecord::Base
  
  has_many :users

  validates :title, uniqueness: true

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = Group.order(sort_clause)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      @group.users << current_user
      redirect_to groups_path, notice: 'New group created.'
    else
      render 'new'
    end
  end    

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])

    if params.include?(:ids)
      if @group.update_users  
        flash[:notice] = 'Users in group updated.'
      else
        flash[:alert] = 'Users in group were not updated.'     
      end
        
    else
      if @group.update(group_params)
        flash[:notice] = 'Group updated.'
      else
        render 'edit'
      end
    end

    redirect_to groups_path

  end

  def destroy
    @group = Group.find(params[:id])
      
      if !@group.users.empty? 
        flash[:alert] = 'Can\'t destroy group. Associated records in users are found.'
      else
        if @group.destroy
          flash[:notice] = 'Group destroyed.'
        else
          flash[:alert] = 'Something went wrong.'
        end
      end
      redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :created_by, user_ids: [])
  end

end  

app/views/groups/_select_users.html.erb
<div class="page-header input-group input-group-sm">
  <p><h3> Add users to group </h3></p>
    <%= form_tag add_users_groups_path, method: :post do %>
      <%= collection_check_boxes :group, :user_ids, User.all, :id, :full_name do |b| %>
		<p>
		  <span class="input-group-addon">
		    <%= b.check_box %>
		  </span>      
		</p>	
      <%= b.label class: "form-control" %>
    <% end %>
    <%= submit_tag 'Add users', class: "btn" %>
  <% end %> 
</div>        

app/views/groups/_update_users.html.erb
<div class="page-header input-group input-group-sm">
  <p><h3> Add users to group </h3></p>
    <%= form_tag group_path, method: :put do %>
      <%= collection_check_boxes :group, :user_ids, User.all, :id, :full_name do |b| %>
		<p>
		  <span class="input-group-addon">
		    <%= b.check_box %>
		  </span>      
		</p>	
      <%= b.label class: "form-control" %>
    <% end %>
    <%= submit_tag 'Update users', class: "btn" %>
  <% end %> 
</div>        

app/views/groups/_users_in_group.html.haml
-obj.each do |user|
  %p= user.full_name

app/views/groups/edit.html.haml
.authform
  = form_for @group, html: {method: :patch, :role => 'form'} do |f|
    %h3 Change group
    - if @group.errors.any?
      #error_explanation
        = render 'shared/messages', obj: @group
    .form-group
      = f.label :name
      = f.text_field :name, autofocus: true, class: 'form-control'
    = f.submit "Change group", :class => 'button right'
    = render "shared/form_nav_links", locals: { back: true }

app/views/groups/edit.js.erb
$('#update_users').html("<%= j (render 'update_users') %>");
$('#update_users').slideDown(350);

app/views/groups/index.html.haml
.container
  .row
    .col-md-3
      #update_users{style: "display:none"}
    .col-md-9
      %h3
        List of groups
        %table.my_table
          %thead
            %tr
              %th= sortable("name", "Title")
              %th= sortable("created_by", "Created by")
              %th Users in group
              %th
          %tbody
            - @groups.each do |group|  
              %tr
                %td= group.name
                %td= group.owner.full_name
                %td
                  - if group.users.any?
                    = render 'users_in_group', obj: group.users
                %td
                  =link_to "Update users | ", edit_group_path(group), remote: true
                  =link_to 'Edit group | ', edit_group_path(group)
                  =link_to 'Destroy group', group_path(group), method: :delete
          %tfoot
            %tr
              %td{:span => 3}
                %strong All groups
              %td
                %strong
                  =@groups.length
              %td
              %td 
      %ul.nav.nav-pills
        %li
          =link_to "New group", new_group_path
        %li.active
          =link_to "Home", root_path

app/views/groups/new.html.haml
.authform
  = form_for @group, html: {:role => 'form'} do |f|
    %h3 New group
    - if @group.errors.any?
      #error_explanation
        = render 'shared/messages', obj: @group
    .form-group
      = f.label :name
      = f.text_field :name, autofocus: true, class: 'form-control'
    .form-group
      = f.text_field :created_by, hidden: "hidden", value: current_user.id

    = f.submit "Add group", :class => 'button right'
    = render "shared/form_nav_links", locals: { back: true }