config/routes.rb
Rails.application.routes.draw do
     
  devise_for :users, controllers: {:registrations => 'admin/registrations', :sessions => 'admin/sessions'}
  
  scope module: 'admin' do
    resources :users, except: [:create]
    resources :users, path: 'my_users', only: [:create]
    resources :departments
    resources :positions
  end

  resources :groups
  resources :company_types
  resources :companies
  resources :contacts
  resources :activity_types
  resources :activities

  get "serve_activities/planned", to: "serve_activities#planned"
  get "serve_activities/completed", to: "serve_activities#completed"

  root to: 'welcome#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
	belongs_to :company_type
	has_many :contacts
  has_many :address, as: :addressable, dependent: :destroy 

	validates :title, :company_type_id, presence: true
	validates_uniqueness_of :title

end

app/models/company_type.rb
class CompanyType < ActiveRecord::Base

has_many :companies

validates :title, presence: true, uniqueness: true

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

	def index
	  @companies = Company.order(sort_clause)
  end

	def new
		@company = Company.new()
	end

	def create
	  @company = Company.new(company_params)
    
    if @company.save 
      redirect_to companies_path, notice: "Company \'#{ @company.title }\' created."
    else
      render "new"
    end

  end

  def edit
  	@company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])

    if @company.update(company_params) 
      redirect_to companies_path, notice: "Company \'#{ @company.title }\' updated."
    else
      render "edit"
    end

  end

  def destroy
  	Company.find(params[:id]).destroy
    redirect_to companies_path, notice: "Company destroyed."
  end
  
  private

  def company_params
    params.require(:company).permit([:title, :full_title, :company_type_id])
  end

end

app/views/companies/_form.html.haml
.form-company
  = f.label :title
  = f.text_field :title, autofocus: true, class: 'form-control'
.form-company
  = f.label :full_title
  = f.text_field :full_title, class: 'form-control'
.form-company
  = f.label :company_type_id
  = f.collection_select :company_type_id, CompanyType.all, :id, :title, class: 'form-control'

app/views/companies/edit.html.haml
.authform
  = form_for @company, html: {method: :patch, :role => 'form'} do |f|
    %h3 Change company
    - if @company.errors.any?
      #error_explanation
        = render 'shared/messages', obj: @company
    = render 'form', f: f
    = f.submit "Change company", :class => 'button right'
    = render "shared/form_nav_links", locals: { back: true }

app/views/companies/index.html.haml
.container
  .row
    .col-md-3
      #company_types{style: "display:none"}
    .col-md-9
      %h3
        Companies
        %table.my_table
          %thead
            %tr
              %th= sortable("title")
              %th= sortable("full_title", "Full title")
              %th= sortable("company_type_id", "Type")
              %th= sortable("created_at", "Created at")
              %th= sortable("updated_at", "Updated at")
              %th
          %tbody
            -@companies.each do |comp|  
              %tr
                %td= comp.title
                %td= comp.full_title
                %td= comp.company_type.title
                %td= comp.created_at
                %td= comp.updated_at
                %td
                  =link_to 'Edit company | ', edit_company_path(comp)
                  =link_to 'Destroy company', company_path(comp), method: :delete
          %tfoot
            %tr
              %td{:span => 4}
                %strong All companies
              %td
                %strong
                  =@companies.length
              %td
      %ul.nav.nav-pills
        %li
          =link_to "New comp", new_company_path
        %li.active
          =link_to "Home", root_path

app/views/companies/new.html.haml
.authform
  = form_for @company, html: {:role => 'form'} do |f|
    %h3 New company
    - if @company.errors.any?
      #error_explanation
        = render 'shared/messages', obj: @company

    = render 'form', f: f
    = f.submit "Add company", :class => 'button right'
    = render "shared/form_nav_links", locals: { back: true }